name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1

    services:
      claims-db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: domaindriven
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
      - name: install packages
        run: sudo apt install libtinfo6 libtinfo-dev
      - name: Deal with libtinfow issue
        run: sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfow.so.6

      - name: Update stack
        run: stack update
      - uses: actions/cache@v2
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
      - name: Build dependencies
        run: |
            stack build domaindriven --only-dependencies --fast

      - uses: actions/cache@v2
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('services/claims/package.yaml') }}
      - name: Build domaindriven
        run: |
            stack build domaindriven --fast
      - name: Run tests
        run: |
            stack test domaindriven --fast

